### ISSUE TITLE
IOError: [Errno 32] Broken pipe  

### ISSUE THREAD

**Issue by Zaab1t** [typeintandem/nvim#1]
When I do `:Tandem` there are no new `:messages`. `:TandemSession` prints `Session ID: None` and editing the buffer will crash with the following error:

``` python
error caught in async handler '/home/zaab/.config/nvim/bundle/nvim/rplugin/python/tandem_neovim.py:autocmd:TextChangedI:* ()'
Traceback (most recent call last):                                                                                           
  File "/home/zaab/.config/nvim/bundle/nvim/rplugin/python/tandem_neovim.py", line 62, in on_text_changed_i
    self._tandem.check_buffer()                                                                            
  File "/home/zaab/.config/nvim/bundle/nvim/rplugin/python/tandem_lib/tandem_plugin.py", line 115, in check_buffer
    self._send_patches(target_buffer_contents)                                                                    
  File "/home/zaab/.config/nvim/bundle/nvim/rplugin/python/tandem_lib/tandem_plugin.py", line 218, in _send_patches
    error()                                                                                                        
  File "/home/zaab/.config/nvim/bundle/nvim/rplugin/python/tandem_lib/tandem_plugin.py", line 213, in _send_patches
    self._agent.stdin.write(m.serialize(message))                                                                  
IOError: [Errno 32] Broken pipe   
```

`:CheckHealth` is perfect and I have python2, python3, nodejs and their neovim packages.

Let me know if you need more information :)

**Comment by geoffxy** [comment]
Thanks for trying Tandem @Zaab1t!

Are there any log files in your `/tmp` directory of the form `tandem-*.log`? If so, could you paste them here so we could take a look?

**Comment by Zaab1t** [comment]
There are none. I tried "hosting" and connecting to another user, but it didn't spawn any log files.

**Comment by geoffxy** [comment]
Hmm, alright. What does your shell return when you run `which python3`? Also what version of Python 3 do you have?

**Comment by Zaab1t** [comment]
`/usr/bin/python3`

`Python 3.5.2`

Also tried setting `let g:python3_host_prog = $HOME . '/usr/bin/python3'` before anything in my config, but that didn't help.

**Comment by wchargin** [comment]
I have the same issue. I added
```diff
diff --git a/rplugin/python/tandem_neovim.py b/rplugin/python/tandem_neovim.py
index ff557a7..58f1ffa 100644
--- a/rplugin/python/tandem_neovim.py
+++ b/rplugin/python/tandem_neovim.py
@@ -27,6 +27,7 @@ class TandemNeovimPlugin(object):
         session_id = args[0] if len(args) >= 1 else None
         self._tandem.start(session_id)
         self._session_id = session_id
+        self._vim.command('echom "%s"' % session_id)
 
     @neovim.command("TandemStop", nargs="*", sync=True)
     def stop(self, args):
```
and it prints `None` in vim. I have `python3==3.5.2`, and `neovim==0.2.4` and `python3-neovim==0.2.4`. The paths and versions reported by `nvim +CheckHealth` are correct. The only health warning is a missing Ruby provider (irrelevant). I have no log files in `/tmp` or elsewhere that I could find. I am running on Mint/Ubuntu 16.04 (and xmonad, if relevant, but I doubt it).

Would love to try this software! Let me know if there is anything that I can do to help debug this.

**Comment by Zaab1t** [comment]
That is odd. I have the same health warning, os (Ubuntu, not mint) and I also run xmonad.
